# CMake generated Testfile for 
# Source directory: D:/S/tudat/Tudat/JsonInterface
# Build directory: D:/S/debug/tudat/Tudat/JsonInterface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_JsonInterfaceAcceleration "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceAcceleration")
add_test(test_JsonInterfaceAerodynamics "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceAerodynamics")
add_test(test_JsonInterfaceAtmosphere "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceAtmosphere")
add_test(test_JsonInterfaceBody "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceBody")
add_test(test_JsonInterfaceDeserialization "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceDeserialization")
add_test(test_JsonInterfaceEphemeris "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceEphemeris")
add_test(test_JsonInterfaceExport "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceExport")
add_test(test_JsonInterfaceGravityField "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceGravityField")
add_test(test_JsonInterfaceGravityFieldVariation "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceGravityFieldVariation")
add_test(test_JsonInterfaceGroundStation "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceGroundStation")
add_test(test_JsonInterfaceIntegrator "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceIntegrator")
add_test(test_JsonInterfaceInterpolation "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceInterpolation")
add_test(test_JsonInterfaceMassRateModel "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceMassRateModel")
add_test(test_JsonInterfacePropagator "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfacePropagator")
add_test(test_JsonInterfaceRadiationPressure "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceRadiationPressure")
add_test(test_JsonInterfaceReferenceFrames "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceReferenceFrames")
add_test(test_JsonInterfaceRotationModel "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceRotationModel")
add_test(test_JsonInterfaceShapeModel "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceShapeModel")
add_test(test_JsonInterfaceSimulationSingleSatellite "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationSingleSatellite")
add_test(test_JsonInterfaceSimulationSinglePerturbedSatellite "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationSinglePerturbedSatellite")
add_test(test_JsonInterfaceSimulationInnerSolarSystem "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationInnerSolarSystem")
add_test(test_JsonInterfaceSimulationGalileoConstellation "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationGalileoConstellation")
add_test(test_JsonInterfaceSimulationThrustAlongVelocityVector "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationThrustAlongVelocityVector")
add_test(test_JsonInterfaceSimulationThrustAccelerationFromFile "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationThrustAccelerationFromFile")
add_test(test_JsonInterfaceSpice "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSpice")
add_test(test_JsonInterfaceState "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceState")
add_test(test_JsonInterfaceTermination "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceTermination")
add_test(test_JsonInterfaceThrust "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceThrust")
add_test(test_JsonInterfaceTorque "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceTorque")
add_test(test_JsonInterfaceVariable "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceVariable")
add_test(test_JsonInterfaceObservation "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceObservation")
add_test(test_JsonInterfaceParameter "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceParameter")
add_test(test_JsonInterfaceSimulationSingleSatelliteVariational "D:/S/tudat/Tudat/../bin/unit_tests/test_JsonInterfaceSimulationSingleSatelliteVariational")
